rm(list=ls())
cat("\014")
library("stringr")
library("tidyverse")
#install.packages("vroom")
#library("xlsx")
#library(readxl)
#df <- read_excel("dados/LeidenRanking2021.xlsx", sheet = 2)
#LeidenRanking2021 <- saveRDS(df, "LeidenRanking2021.Rds")
data <- readRDS("dados/LeidenRanking2021.Rds")
data <- as.data.frame(data)
data$Per_Init <- str_sub(data$Period,1,4)
data$Per_End <- str_sub(data$Period,6,9)
#list_of_files <- list.files(path = ".", recursive = TRUE,
#                            pattern = "\\.txt$",
#                            full.names = TRUE)
LatLong <- fread("dados/LatLongCountry.txt", header = FALSE, sep = "\t", dec = ".")
names(LatLong) <- c("Siglas", "latitude", "longitude", "Country")
data <- left_join(data, LatLong, by="Country")
rm(LatLong)
data <- data %>% select(c(1:2,89:91, 4, 87:88, 3, 5:86))
#Funcao para remover acentos
data$University <- abjutils::rm_accent(data$University)
data$Country    <- abjutils::rm_accent(data$Country   )
data$Field      <- abjutils::rm_accent(data$Field     )
#Apagar Espacos antes e apos o texto
data$University <- str_trim(data$University, side = c("both", "left", "right"))
data$University <- str_squish(data$University)
data$Country <- str_trim(data$Country, side = c("both", "left", "right"))
data$Country <- str_squish(data$Country)
data$Field   <- str_trim(data$Field, side = c("both", "left", "right"))
data$Field   <- str_squish(data$Field)
#Transformar tudo em letras maiusculas
data$University <- str_to_upper(data$University)
data$Country  <- str_to_upper(data$Country)
data$Field   <- str_to_upper(data$Field)
data$impact_P <- if_else(data$Frac_counting=="0",round(data$impact_P),data$impact_P) 
data$P_top1 <- if_else(data$Frac_counting=="0",round(data$P_top1),data$P_top1) 
data$P_top5 <- if_else(data$Frac_counting=="0",round(data$P_top5),data$P_top5) 
data$P_top10 <- if_else(data$Frac_counting=="0",round(data$P_top10),data$P_top10) 
data$P_top50 <- if_else(data$Frac_counting=="0",round(data$P_top50),data$P_top50)
data$P_collab <- if_else(data$Frac_counting=="0",round(data$P_top50),data$P_top50)
data$P_int_collab        <- if_else(data$Frac_counting=="0",round(data$P_int_collab        ),data$P_int_collab        )
data$P_industry_collab   <- if_else(data$Frac_counting=="0",round(data$P_industry_collab   ),data$P_industry_collab   )
data$P_short_dist_collab <- if_else(data$Frac_counting=="0",round(data$P_short_dist_collab ),data$P_short_dist_collab )
data$P_long_dist_collab  <- if_else(data$Frac_counting=="0",round(data$P_long_dist_collab  ),data$P_long_dist_collab  )
data$P_OA                <- if_else(data$Frac_counting=="0",round(data$P_OA                ),data$P_OA                )
data$P_gold_OA           <- if_else(data$Frac_counting=="0",round(data$P_gold_OA           ),data$P_gold_OA           )
data$P_hybrid_OA         <- if_else(data$Frac_counting=="0",round(data$P_hybrid_OA         ),data$P_hybrid_OA         )
data$P_bronze_OA         <- if_else(data$Frac_counting=="0",round(data$P_bronze_OA         ),data$P_bronze_OA         )
data$P_green_OA          <- if_else(data$Frac_counting=="0",round(data$P_green_OA          ),data$P_green_OA          )
data$P_OA_unknown        <- if_else(data$Frac_counting=="0",round(data$P_OA_unknown        ),data$P_OA_unknown        )
data <- modify_if(data, ~is.numeric(.), ~round(., 2))
data$year <- "2020"
saveRDS(data, file="dados/LeidenRanking2021.Rds")
###########################################
data2021 <- readRDS("dados/LeidenRanking2021.Rds")
dados2020 <- readRDS("dados/LeidenRanking2020.Rds")
LeidenRanking <- rbind(dados2020,data2021)
rm(dados2020, data2021)
saveRDS(LeidenRanking, file="dados/LeidenRanking.Rds")
unique(LeidenRanking$University)
