#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

# Define UI for application
shinyUI(fluidPage(
    navbarPage(title="Leiden Ranking",
               tabPanel("Descrição",
                        tabsetPanel(
                            tabPanel("Sobre o Dashboard",
                                     fluidRow(
                                         column(12,
                                                DT::dataTableOutput("table1")))),
                            ##
                            tabPanel("Banco de Dados",
                                     fluidRow(column(3, 
                                                     selectInput("Opções", 
                                                                 strong("Escolha uma opção:"), 
                                                                 choices=c("Opção 1"="age2",
                                                                           "Opção 2"="age3"),
                                                                 selected = "age2")),
                                              column(9,
                                                plotlyOutput("plot1", height = 800)))),
                            
                            ##
                            tabPanel("subMenu3",
                                     fluidRow(column(3, 
                                                     selectInput("options", 
                                                                 strong("Escolha uma opção:"), 
                                                                 choices=c("UFV"="UNIVERSIDADE FEDERAL DE VICOSA",
                                                                           "UFPB"="FEDERAL UNIVERSITY OF PARAIBA",
                                                                           "UFPE"="FEDERAL UNIVERSITY OF PERNAMBUCO"),
                                                                 selected = "age2")),
                                              column(9,
                                                     plotlyOutput("plot11", height = 800))))
                            
                        )# barra de navegacao interna
                    ),# barra de navegacao superior (Dados do Participante)
               
               tabPanel("Menu2",
                        tabsetPanel(
                          ##
                          tabPanel("SubMenu2.1",
                                   fluidRow(column(9,
                                                   leafletOutput("plot2", height = 600)))),
                          tabPanel("SubMenu2.2",
                                   fluidRow(column(9,
                                                   plotlyOutput("plot3", height = 600))))
                          
                          
                        )# barra de navegacao interna
               ),# barra de navegacao superior (Dados da Escola)
               
               tabPanel("Menu3",
                        tabsetPanel(
                          ##
                          tabPanel("SubMenu3.1",
                                   fluidRow(column(9,
                                                   leafletOutput("plot4", height = 600)))),
                          tabPanel("SubMenu3.2",
                                   fluidRow(column(9,
                                                   plotlyOutput("plot5", height = 600))))
                          
                          
                        )# barra de navegacao interna
               ),# barra de navegacao superior (Dados da Escola)
               
               tabPanel("Indicadores de Impacto Científico",
                        tabsetPanel(
                          ##
                          tabPanel("P_Top1",
                                   fluidRow(column(9,
                                                   selectInput("frac",
                                                               strong("Escolha uma opção:"),
                                                               choices = c("Contagem fracionada" = "1",
                                                                           "Contagem não fracionada" = "0")),
                                                   selectInput("options1", 
                                                               strong("Escolha uma opção:"), 
                                                               choices=c("FEDERAL UNIVERSITY OF PARAIBA",
                                                                          "FEDERAL UNIVERSITY OF PERNAMBUCO",        
                                                                          "FEDERAL UNIVERSITY OF RIO GRANDE DO NORTE" ,
                                                                          "FEDERAL UNIVERSITY OF RIO GRANDE DO SUL",  
                                                                          "FEDERAL UNIVERSITY OF SANTA MARIA",
                                                                          "FEDERAL UNIVERSITY OF SAO CARLOS",         
                                                                          "FEDERAL UNIVERSITY OF UBERLANDIA",
                                                                          "RIO DE JANEIRO STATE UNIVERSITY",          
                                                                          "STATE UNIVERSITY OF MARINGA",               
                                                                          "UNIVERSIDADE DE BRASILIA",                 
                                                                          "UNIVERSIDADE ESTADUAL PAULISTA",
                                                                          "UNIVERSIDADE FEDERAL DA BAHIA",            
                                                                          "UNIVERSIDADE FEDERAL DE GOIAS",
                                                                          "UNIVERSIDADE FEDERAL DE MINAS GERAIS",     
                                                                          "UNIVERSIDADE FEDERAL DE SANTA CATARINA",
                                                                          "UNIVERSIDADE FEDERAL DE SAO PAULO",   
                                                                          "UNIVERSIDADE FEDERAL DE VICOSA",
                                                                          "UNIVERSIDADE FEDERAL DO CEARA",            
                                                                          "UNIVERSIDADE FEDERAL DO PARANA",
                                                                          "UNIVERSIDADE FEDERAL DO RIO DE JANEIRO",   
                                                                          "UNIVERSIDADE FEDERAL FLUMINENSE",
                                                                          "UNIVERSITY OF CAMPINAS",                   
                                                                          "UNIVERSITY OF SAO PAULO"),
                                                               selected = "age2")),
                                            column(9,
                                                   plotlyOutput("plot6", height = 1050)))),
                          tabPanel("PP_Top1",
                                   fluidRow(column(9,
                                                   selectInput("frac7",
                                                               strong("Escolha uma opção:"),
                                                               choices = c("Contagem fracionada" = "1",
                                                                           "Contagem não fracionada" = "0")),
                                                   selectInput("options7", 
                                                               strong("Escolha uma opção:"), 
                                                               choices=c("FEDERAL UNIVERSITY OF PARAIBA",
                                                                         "FEDERAL UNIVERSITY OF PERNAMBUCO",        
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO NORTE" ,
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO SUL",  
                                                                         "FEDERAL UNIVERSITY OF SANTA MARIA",
                                                                         "FEDERAL UNIVERSITY OF SAO CARLOS",         
                                                                         "FEDERAL UNIVERSITY OF UBERLANDIA",
                                                                         "RIO DE JANEIRO STATE UNIVERSITY",          
                                                                         "STATE UNIVERSITY OF MARINGA",               
                                                                         "UNIVERSIDADE DE BRASILIA",                 
                                                                         "UNIVERSIDADE ESTADUAL PAULISTA",
                                                                         "UNIVERSIDADE FEDERAL DA BAHIA",            
                                                                         "UNIVERSIDADE FEDERAL DE GOIAS",
                                                                         "UNIVERSIDADE FEDERAL DE MINAS GERAIS",     
                                                                         "UNIVERSIDADE FEDERAL DE SANTA CATARINA",
                                                                         "UNIVERSIDADE FEDERAL DE SAO PAULO",   
                                                                         "UNIVERSIDADE FEDERAL DE VICOSA",
                                                                         "UNIVERSIDADE FEDERAL DO CEARA",            
                                                                         "UNIVERSIDADE FEDERAL DO PARANA",
                                                                         "UNIVERSIDADE FEDERAL DO RIO DE JANEIRO",   
                                                                         "UNIVERSIDADE FEDERAL FLUMINENSE",
                                                                         "UNIVERSITY OF CAMPINAS",                   
                                                                         "UNIVERSITY OF SAO PAULO"),
                                                               selected = "age2")),
                                            column(9,
                                                   plotlyOutput("plot13", height = 1050)))),
                          tabPanel("P_Top5",
                                   fluidRow(column(9,
                                                   selectInput("frac2",
                                                               strong("Escolha uma opção:"),
                                                               choices = c("Contagem fracionada" = "1",
                                                                           "Contagem não fracionada" = "0")),
                                                   selectInput("options2", 
                                                               strong("Escolha uma opção:"), 
                                                               choices=c("FEDERAL UNIVERSITY OF PARAIBA",
                                                                         "FEDERAL UNIVERSITY OF PERNAMBUCO",        
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO NORTE" ,
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO SUL",  
                                                                         "FEDERAL UNIVERSITY OF SANTA MARIA",
                                                                         "FEDERAL UNIVERSITY OF SAO CARLOS",         
                                                                         "FEDERAL UNIVERSITY OF UBERLANDIA",
                                                                         "RIO DE JANEIRO STATE UNIVERSITY",          
                                                                         "STATE UNIVERSITY OF MARINGA",               
                                                                         "UNIVERSIDADE DE BRASILIA",                 
                                                                         "UNIVERSIDADE ESTADUAL PAULISTA",
                                                                         "UNIVERSIDADE FEDERAL DA BAHIA",            
                                                                         "UNIVERSIDADE FEDERAL DE GOIAS",
                                                                         "UNIVERSIDADE FEDERAL DE MINAS GERAIS",     
                                                                         "UNIVERSIDADE FEDERAL DE SANTA CATARINA",
                                                                         "UNIVERSIDADE FEDERAL DE SAO PAULO",   
                                                                         "UNIVERSIDADE FEDERAL DE VICOSA",
                                                                         "UNIVERSIDADE FEDERAL DO CEARA",            
                                                                         "UNIVERSIDADE FEDERAL DO PARANA",
                                                                         "UNIVERSIDADE FEDERAL DO RIO DE JANEIRO",   
                                                                         "UNIVERSIDADE FEDERAL FLUMINENSE",
                                                                         "UNIVERSITY OF CAMPINAS",                   
                                                                         "UNIVERSITY OF SAO PAULO"),
                                                               selected = "age2")),
                                            column(9,
                                                   plotlyOutput("plot7", height = 1050)))),
                          tabPanel("PP_Top5",
                                   fluidRow(column(9,
                                                   selectInput("frac8",
                                                               strong("Escolha uma opção:"),
                                                               choices = c("Contagem fracionada" = "1",
                                                                           "Contagem não fracionada" = "0")),
                                                   selectInput("options8", 
                                                               strong("Escolha uma opção:"), 
                                                               choices=c("FEDERAL UNIVERSITY OF PARAIBA",
                                                                         "FEDERAL UNIVERSITY OF PERNAMBUCO",        
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO NORTE" ,
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO SUL",  
                                                                         "FEDERAL UNIVERSITY OF SANTA MARIA",
                                                                         "FEDERAL UNIVERSITY OF SAO CARLOS",         
                                                                         "FEDERAL UNIVERSITY OF UBERLANDIA",
                                                                         "RIO DE JANEIRO STATE UNIVERSITY",          
                                                                         "STATE UNIVERSITY OF MARINGA",               
                                                                         "UNIVERSIDADE DE BRASILIA",                 
                                                                         "UNIVERSIDADE ESTADUAL PAULISTA",
                                                                         "UNIVERSIDADE FEDERAL DA BAHIA",            
                                                                         "UNIVERSIDADE FEDERAL DE GOIAS",
                                                                         "UNIVERSIDADE FEDERAL DE MINAS GERAIS",     
                                                                         "UNIVERSIDADE FEDERAL DE SANTA CATARINA",
                                                                         "UNIVERSIDADE FEDERAL DE SAO PAULO",   
                                                                         "UNIVERSIDADE FEDERAL DE VICOSA",
                                                                         "UNIVERSIDADE FEDERAL DO CEARA",            
                                                                         "UNIVERSIDADE FEDERAL DO PARANA",
                                                                         "UNIVERSIDADE FEDERAL DO RIO DE JANEIRO",   
                                                                         "UNIVERSIDADE FEDERAL FLUMINENSE",
                                                                         "UNIVERSITY OF CAMPINAS",                   
                                                                         "UNIVERSITY OF SAO PAULO"),
                                                               selected = "age2")),
                                            column(9,
                                                   plotlyOutput("plot14", height = 800)))),
                          tabPanel("P_Top10",
                                   fluidRow(column(9,
                                                   selectInput("frac3",
                                                               strong("Escolha uma opção:"),
                                                               choices = c("Contagem fracionada" = "1",
                                                                           "Contagem não fracionada" = "0")),
                                                   selectInput("options3", 
                                                               strong("Escolha uma opção:"), 
                                                               choices=c("FEDERAL UNIVERSITY OF PARAIBA",
                                                                         "FEDERAL UNIVERSITY OF PERNAMBUCO",        
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO NORTE" ,
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO SUL",  
                                                                         "FEDERAL UNIVERSITY OF SANTA MARIA",
                                                                         "FEDERAL UNIVERSITY OF SAO CARLOS",         
                                                                         "FEDERAL UNIVERSITY OF UBERLANDIA",
                                                                         "RIO DE JANEIRO STATE UNIVERSITY",          
                                                                         "STATE UNIVERSITY OF MARINGA",               
                                                                         "UNIVERSIDADE DE BRASILIA",                 
                                                                         "UNIVERSIDADE ESTADUAL PAULISTA",
                                                                         "UNIVERSIDADE FEDERAL DA BAHIA",            
                                                                         "UNIVERSIDADE FEDERAL DE GOIAS",
                                                                         "UNIVERSIDADE FEDERAL DE MINAS GERAIS",     
                                                                         "UNIVERSIDADE FEDERAL DE SANTA CATARINA",
                                                                         "UNIVERSIDADE FEDERAL DE SAO PAULO",   
                                                                         "UNIVERSIDADE FEDERAL DE VICOSA",
                                                                         "UNIVERSIDADE FEDERAL DO CEARA",            
                                                                         "UNIVERSIDADE FEDERAL DO PARANA",
                                                                         "UNIVERSIDADE FEDERAL DO RIO DE JANEIRO",   
                                                                         "UNIVERSIDADE FEDERAL FLUMINENSE",
                                                                         "UNIVERSITY OF CAMPINAS",                   
                                                                         "UNIVERSITY OF SAO PAULO"),
                                                               selected = "age2")),
                                            column(9,
                                                   plotlyOutput("plot8", height = 1050)))),
                          tabPanel("PP_Top10",
                                   fluidRow(column(9,
                                                   selectInput("frac9",
                                                               strong("Escolha uma opção:"),
                                                               choices = c("Contagem fracionada" = "1",
                                                                           "Contagem não fracionada" = "0")),
                                                   selectInput("options9", 
                                                               strong("Escolha uma opção:"), 
                                                               choices=c("FEDERAL UNIVERSITY OF PARAIBA",
                                                                         "FEDERAL UNIVERSITY OF PERNAMBUCO",        
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO NORTE" ,
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO SUL",  
                                                                         "FEDERAL UNIVERSITY OF SANTA MARIA",
                                                                         "FEDERAL UNIVERSITY OF SAO CARLOS",         
                                                                         "FEDERAL UNIVERSITY OF UBERLANDIA",
                                                                         "RIO DE JANEIRO STATE UNIVERSITY",          
                                                                         "STATE UNIVERSITY OF MARINGA",               
                                                                         "UNIVERSIDADE DE BRASILIA",                 
                                                                         "UNIVERSIDADE ESTADUAL PAULISTA",
                                                                         "UNIVERSIDADE FEDERAL DA BAHIA",            
                                                                         "UNIVERSIDADE FEDERAL DE GOIAS",
                                                                         "UNIVERSIDADE FEDERAL DE MINAS GERAIS",     
                                                                         "UNIVERSIDADE FEDERAL DE SANTA CATARINA",
                                                                         "UNIVERSIDADE FEDERAL DE SAO PAULO",   
                                                                         "UNIVERSIDADE FEDERAL DE VICOSA",
                                                                         "UNIVERSIDADE FEDERAL DO CEARA",            
                                                                         "UNIVERSIDADE FEDERAL DO PARANA",
                                                                         "UNIVERSIDADE FEDERAL DO RIO DE JANEIRO",   
                                                                         "UNIVERSIDADE FEDERAL FLUMINENSE",
                                                                         "UNIVERSITY OF CAMPINAS",                   
                                                                         "UNIVERSITY OF SAO PAULO"),
                                                               selected = "age2")),
                                            column(9,
                                                   plotlyOutput("plot15", height = 800)))),
                          tabPanel("P_Top50",
                                   fluidRow(column(9,
                                                   selectInput("frac4",
                                                               strong("Escolha uma opção:"),
                                                               choices = c("Contagem fracionada" = "1",
                                                                           "Contagem não fracionada" = "0")),
                                                   selectInput("options4", 
                                                               strong("Escolha uma opção:"), 
                                                               choices=c("FEDERAL UNIVERSITY OF PARAIBA",
                                                                         "FEDERAL UNIVERSITY OF PERNAMBUCO",        
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO NORTE" ,
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO SUL",  
                                                                         "FEDERAL UNIVERSITY OF SANTA MARIA",
                                                                         "FEDERAL UNIVERSITY OF SAO CARLOS",         
                                                                         "FEDERAL UNIVERSITY OF UBERLANDIA",
                                                                         "RIO DE JANEIRO STATE UNIVERSITY",          
                                                                         "STATE UNIVERSITY OF MARINGA",               
                                                                         "UNIVERSIDADE DE BRASILIA",                 
                                                                         "UNIVERSIDADE ESTADUAL PAULISTA",
                                                                         "UNIVERSIDADE FEDERAL DA BAHIA",            
                                                                         "UNIVERSIDADE FEDERAL DE GOIAS",
                                                                         "UNIVERSIDADE FEDERAL DE MINAS GERAIS",     
                                                                         "UNIVERSIDADE FEDERAL DE SANTA CATARINA",
                                                                         "UNIVERSIDADE FEDERAL DE SAO PAULO",   
                                                                         "UNIVERSIDADE FEDERAL DE VICOSA",
                                                                         "UNIVERSIDADE FEDERAL DO CEARA",            
                                                                         "UNIVERSIDADE FEDERAL DO PARANA",
                                                                         "UNIVERSIDADE FEDERAL DO RIO DE JANEIRO",   
                                                                         "UNIVERSIDADE FEDERAL FLUMINENSE",
                                                                         "UNIVERSITY OF CAMPINAS",                   
                                                                         "UNIVERSITY OF SAO PAULO"),
                                                               selected = "age2")),
                                            column(9,
                                                   plotlyOutput("plot9", height = 1050)))),
                          tabPanel("PP_Top50",
                                   fluidRow(column(9,
                                                   selectInput("frac10",
                                                               strong("Escolha uma opção:"),
                                                               choices = c("Contagem fracionada" = "1",
                                                                           "Contagem não fracionada" = "0")),
                                                   selectInput("options10", 
                                                               strong("Escolha uma opção:"), 
                                                               choices=c("FEDERAL UNIVERSITY OF PARAIBA",
                                                                         "FEDERAL UNIVERSITY OF PERNAMBUCO",        
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO NORTE" ,
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO SUL",  
                                                                         "FEDERAL UNIVERSITY OF SANTA MARIA",
                                                                         "FEDERAL UNIVERSITY OF SAO CARLOS",         
                                                                         "FEDERAL UNIVERSITY OF UBERLANDIA",
                                                                         "RIO DE JANEIRO STATE UNIVERSITY",          
                                                                         "STATE UNIVERSITY OF MARINGA",               
                                                                         "UNIVERSIDADE DE BRASILIA",                 
                                                                         "UNIVERSIDADE ESTADUAL PAULISTA",
                                                                         "UNIVERSIDADE FEDERAL DA BAHIA",            
                                                                         "UNIVERSIDADE FEDERAL DE GOIAS",
                                                                         "UNIVERSIDADE FEDERAL DE MINAS GERAIS",     
                                                                         "UNIVERSIDADE FEDERAL DE SANTA CATARINA",
                                                                         "UNIVERSIDADE FEDERAL DE SAO PAULO",   
                                                                         "UNIVERSIDADE FEDERAL DE VICOSA",
                                                                         "UNIVERSIDADE FEDERAL DO CEARA",            
                                                                         "UNIVERSIDADE FEDERAL DO PARANA",
                                                                         "UNIVERSIDADE FEDERAL DO RIO DE JANEIRO",   
                                                                         "UNIVERSIDADE FEDERAL FLUMINENSE",
                                                                         "UNIVERSITY OF CAMPINAS",                   
                                                                         "UNIVERSITY OF SAO PAULO"),
                                                               selected = "age2")),
                                            column(9,
                                                   plotlyOutput("plot16", height = 800)))),
                          tabPanel("TCS",
                                   fluidRow(column(9,
                                                   selectInput("frac5",
                                                               strong("Escolha uma opção:"),
                                                               choices = c("Contagem fracionada" = "1",
                                                                           "Contagem não fracionada" = "0")),
                                                   selectInput("options5", 
                                                               strong("Escolha uma opção:"), 
                                                               choices=c("FEDERAL UNIVERSITY OF PARAIBA",
                                                                         "FEDERAL UNIVERSITY OF PERNAMBUCO",        
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO NORTE" ,
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO SUL",  
                                                                         "FEDERAL UNIVERSITY OF SANTA MARIA",
                                                                         "FEDERAL UNIVERSITY OF SAO CARLOS",         
                                                                         "FEDERAL UNIVERSITY OF UBERLANDIA",
                                                                         "RIO DE JANEIRO STATE UNIVERSITY",          
                                                                         "STATE UNIVERSITY OF MARINGA",               
                                                                         "UNIVERSIDADE DE BRASILIA",                 
                                                                         "UNIVERSIDADE ESTADUAL PAULISTA",
                                                                         "UNIVERSIDADE FEDERAL DA BAHIA",            
                                                                         "UNIVERSIDADE FEDERAL DE GOIAS",
                                                                         "UNIVERSIDADE FEDERAL DE MINAS GERAIS",     
                                                                         "UNIVERSIDADE FEDERAL DE SANTA CATARINA",
                                                                         "UNIVERSIDADE FEDERAL DE SAO PAULO",   
                                                                         "UNIVERSIDADE FEDERAL DE VICOSA",
                                                                         "UNIVERSIDADE FEDERAL DO CEARA",            
                                                                         "UNIVERSIDADE FEDERAL DO PARANA",
                                                                         "UNIVERSIDADE FEDERAL DO RIO DE JANEIRO",   
                                                                         "UNIVERSIDADE FEDERAL FLUMINENSE",
                                                                         "UNIVERSITY OF CAMPINAS",                   
                                                                         "UNIVERSITY OF SAO PAULO"),
                                                               selected = "age2")),
                                            column(9,
                                                   plotlyOutput("plot10", height = 800)))),
                          tabPanel("TNCS",
                                   fluidRow(column(9,
                                                   selectInput("frac11",
                                                               strong("Escolha uma opção:"),
                                                               choices = c("Contagem fracionada" = "1",
                                                                           "Contagem não fracionada" = "0")),
                                                   selectInput("options11", 
                                                               strong("Escolha uma opção:"), 
                                                               choices=c("FEDERAL UNIVERSITY OF PARAIBA",
                                                                         "FEDERAL UNIVERSITY OF PERNAMBUCO",        
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO NORTE" ,
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO SUL",  
                                                                         "FEDERAL UNIVERSITY OF SANTA MARIA",
                                                                         "FEDERAL UNIVERSITY OF SAO CARLOS",         
                                                                         "FEDERAL UNIVERSITY OF UBERLANDIA",
                                                                         "RIO DE JANEIRO STATE UNIVERSITY",          
                                                                         "STATE UNIVERSITY OF MARINGA",               
                                                                         "UNIVERSIDADE DE BRASILIA",                 
                                                                         "UNIVERSIDADE ESTADUAL PAULISTA",
                                                                         "UNIVERSIDADE FEDERAL DA BAHIA",            
                                                                         "UNIVERSIDADE FEDERAL DE GOIAS",
                                                                         "UNIVERSIDADE FEDERAL DE MINAS GERAIS",     
                                                                         "UNIVERSIDADE FEDERAL DE SANTA CATARINA",
                                                                         "UNIVERSIDADE FEDERAL DE SAO PAULO",   
                                                                         "UNIVERSIDADE FEDERAL DE VICOSA",
                                                                         "UNIVERSIDADE FEDERAL DO CEARA",            
                                                                         "UNIVERSIDADE FEDERAL DO PARANA",
                                                                         "UNIVERSIDADE FEDERAL DO RIO DE JANEIRO",   
                                                                         "UNIVERSIDADE FEDERAL FLUMINENSE",
                                                                         "UNIVERSITY OF CAMPINAS",                   
                                                                         "UNIVERSITY OF SAO PAULO"),
                                                               selected = "age2")),
                                            column(9,
                                                   plotlyOutput("plot17", height = 1050)))),
                          tabPanel("MCS",
                                   fluidRow(column(9,
                                                   selectInput("frac6",
                                                               strong("Escolha uma opção:"),
                                                               choices = c("Contagem fracionada" = "1",
                                                                           "Contagem não fracionada" = "0")),
                                                   selectInput("options6", 
                                                               strong("Escolha uma opção:"), 
                                                               choices=c("FEDERAL UNIVERSITY OF PARAIBA",
                                                                         "FEDERAL UNIVERSITY OF PERNAMBUCO",        
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO NORTE" ,
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO SUL",  
                                                                         "FEDERAL UNIVERSITY OF SANTA MARIA",
                                                                         "FEDERAL UNIVERSITY OF SAO CARLOS",         
                                                                         "FEDERAL UNIVERSITY OF UBERLANDIA",
                                                                         "RIO DE JANEIRO STATE UNIVERSITY",          
                                                                         "STATE UNIVERSITY OF MARINGA",               
                                                                         "UNIVERSIDADE DE BRASILIA",                 
                                                                         "UNIVERSIDADE ESTADUAL PAULISTA",
                                                                         "UNIVERSIDADE FEDERAL DA BAHIA",            
                                                                         "UNIVERSIDADE FEDERAL DE GOIAS",
                                                                         "UNIVERSIDADE FEDERAL DE MINAS GERAIS",     
                                                                         "UNIVERSIDADE FEDERAL DE SANTA CATARINA",
                                                                         "UNIVERSIDADE FEDERAL DE SAO PAULO",   
                                                                         "UNIVERSIDADE FEDERAL DE VICOSA",
                                                                         "UNIVERSIDADE FEDERAL DO CEARA",            
                                                                         "UNIVERSIDADE FEDERAL DO PARANA",
                                                                         "UNIVERSIDADE FEDERAL DO RIO DE JANEIRO",   
                                                                         "UNIVERSIDADE FEDERAL FLUMINENSE",
                                                                         "UNIVERSITY OF CAMPINAS",                   
                                                                         "UNIVERSITY OF SAO PAULO"),
                                                               selected = "age2")),
                                            column(9,
                                                   plotlyOutput("plot12", height = 800)))),
                          tabPanel("MNCS",
                                   fluidRow(column(9,
                                                   selectInput("frac12",
                                                               strong("Escolha uma opção:"),
                                                               choices = c("Contagem fracionada" = "1",
                                                                           "Contagem não fracionada" = "0")),
                                                   selectInput("options12", 
                                                               strong("Escolha uma opção:"), 
                                                               choices=c("FEDERAL UNIVERSITY OF PARAIBA",
                                                                         "FEDERAL UNIVERSITY OF PERNAMBUCO",        
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO NORTE" ,
                                                                         "FEDERAL UNIVERSITY OF RIO GRANDE DO SUL",  
                                                                         "FEDERAL UNIVERSITY OF SANTA MARIA",
                                                                         "FEDERAL UNIVERSITY OF SAO CARLOS",         
                                                                         "FEDERAL UNIVERSITY OF UBERLANDIA",
                                                                         "RIO DE JANEIRO STATE UNIVERSITY",          
                                                                         "STATE UNIVERSITY OF MARINGA",               
                                                                         "UNIVERSIDADE DE BRASILIA",                 
                                                                         "UNIVERSIDADE ESTADUAL PAULISTA",
                                                                         "UNIVERSIDADE FEDERAL DA BAHIA",            
                                                                         "UNIVERSIDADE FEDERAL DE GOIAS",
                                                                         "UNIVERSIDADE FEDERAL DE MINAS GERAIS",     
                                                                         "UNIVERSIDADE FEDERAL DE SANTA CATARINA",
                                                                         "UNIVERSIDADE FEDERAL DE SAO PAULO",   
                                                                         "UNIVERSIDADE FEDERAL DE VICOSA",
                                                                         "UNIVERSIDADE FEDERAL DO CEARA",            
                                                                         "UNIVERSIDADE FEDERAL DO PARANA",
                                                                         "UNIVERSIDADE FEDERAL DO RIO DE JANEIRO",   
                                                                         "UNIVERSIDADE FEDERAL FLUMINENSE",
                                                                         "UNIVERSITY OF CAMPINAS",                   
                                                                         "UNIVERSITY OF SAO PAULO"),
                                                               selected = "age2")),
                                            column(9,
                                                   plotlyOutput("plot18", height = 1050))))
                          
                        )# barra de navegacao interna
               )# barra de navegacao superior (Dados da Escola)
               
    )#navbarPage
)#fluidPage
)#shinyUI