

Instituicao <- function(University){
  # NOTE:"app_string" and "value" must have the same order
  Universidade <-  c("UFLA"   ,
                     "UFMT"   ,
                     "UFPA"   ,
                     "UFPB"   ,
                     "UFPel"  ,
                     "UFPE"   ,
                     "UFRN"   ,
                     "UFRGS"  ,
                     "UFSM"   ,
                     "UFSCAR" ,
                     "UFU"    ,
                     "UEL"    ,
                     "UERJ"   ,
                     "UEM"    ,
                     "UNB"    ,
                     "UNESP"  ,
                     "UFBA"   ,
                     "UFG"    ,
                     "UFJF"   ,
                     "UFMG"   ,
                     "UFSC"   ,
                     "UNIFESP",
                     "UFV"    ,
                     "UFC"    ,
                     "UFES"   ,
                     "UFPR"   ,
                     "UFRJ"   ,
                     "UFF"    ,
                     "UNICAMP",
                     "USP"    )
  pos        <- which(University==Universidade)
  value      <- c("FEDERAL UNIVERSITY OF LAVRAS"             ,
                  "FEDERAL UNIVERSITY OF MATO GROSSO"        ,
                  "FEDERAL UNIVERSITY OF PARA"               ,
                  "FEDERAL UNIVERSITY OF PARAIBA"            ,
                  "FEDERAL UNIVERSITY OF PELOTAS"            ,
                  "FEDERAL UNIVERSITY OF PERNAMBUCO"         ,
                  "FEDERAL UNIVERSITY OF RIO GRANDE DO NORTE",
                  "FEDERAL UNIVERSITY OF RIO GRANDE DO SUL"  ,
                  "FEDERAL UNIVERSITY OF SANTA MARIA"        ,
                  "FEDERAL UNIVERSITY OF SAO CARLOS"         ,
                  "FEDERAL UNIVERSITY OF UBERLANDIA"         ,
                  "LONDRINA STATE UNIVERSITY"                ,
                  "RIO DE JANEIRO STATE UNIVERSITY"          ,
                  "STATE UNIVERSITY OF MARINGA"              ,
                  "UNIVERSIDADE DE BRASILIA"                 ,
                  "UNIVERSIDADE ESTADUAL PAULISTA"           ,
                  "UNIVERSIDADE FEDERAL DA BAHIA"            ,
                  "UNIVERSIDADE FEDERAL DE GOIAS"            ,
                  "UNIVERSIDADE FEDERAL DE JUIZ DE FORA"     ,
                  "UNIVERSIDADE FEDERAL DE MINAS GERAIS"     ,
                  "UNIVERSIDADE FEDERAL DE SANTA CATARINA"   ,
                  "UNIVERSIDADE FEDERAL DE SAO PAULO"        ,
                  "UNIVERSIDADE FEDERAL DE VICOSA"           ,
                  "UNIVERSIDADE FEDERAL DO CEARA"            ,
                  "UNIVERSIDADE FEDERAL DO ESPIRITO SANTO"   ,
                  "UNIVERSIDADE FEDERAL DO PARANA"           ,
                  "UNIVERSIDADE FEDERAL DO RIO DE JANEIRO"   ,
                  "UNIVERSIDADE FEDERAL FLUMINENSE"          ,
                  "UNIVERSITY OF CAMPINAS"                   ,
                  "UNIVERSITY OF SAO PAULO")[pos]
  return(value)
}
Instituicao("UNIFESP")
